### ISSUE TITLE
后台管理获取所有文章的sql语句有问题

### ISSUE THREAD

**Issue by mabu233** [hlerenow/HEL#4]
select `eid` from relationships r where r.mid=128
relationships 表并没有 eid，应该是nid

分页也还没做
项目挺不错的，怎么不继续开发了？

**Comment by hlerenow** [comment]
- sql 语句 不存在问题，使用的是字段的别名
- 分页功能有做，现在已修复
- 最近没时间做，工作太忙了，之后应该会抽时间，将未实现的功能全部实现，这半年的工作也让我对这个系统的实现有了更好的想法，waiting
